FROM mcr.microsoft.com/devcontainers/rust:latest

RUN sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)" 
# && export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH" && cargo install --git https://github.com/coral-xyz/anchor avm --force && avm install latest && avm use latest && npm install --global yarn
